e1:
	g++ -Wall -std=c++11 e1.cpp -o e1.o
e2:
	g++ -Wall -std=c++11 e2.cpp -o e2.o
e3:
	g++ -Wall -std=c++11 e3.cpp -o e3.o
e4:
	g++ -Wall -std=c++11 e4.cpp -o e4.o
e5:
	g++ -Wall -std=c++11 e5.cpp -o e5.o
e6:
	g++ -Wall -std=c++11 e6.cpp -o e6.o

clean:
	rm -f *.o
