5.5.1:
	g++ -Wall -std=c++11 5.5.1.cpp -o 5.5.1.o

5.5.1.2:
	g++ -Wall -std=c++11 5.5.1.2.cpp -o 5.5.1.2.o

5.5.2:
	g++ -Wall -std=c++11 5.5.2.cpp -o 5.5.2.o

5.5.3:
	g++ -Wall -std=c++11 5.5.3.cpp -o 5.5.3.o

5.5.4:
	g++ -Wall -std=c++11 5.5.4.cpp -o 5.5.4.o

clean:
	rm -f *.o
